spring:
  profiles: local 

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: validate
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gongdb-admin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: my-secret-pw

file:
  path: /files
